simulation:
    Ts: 6
    tSample: 300
neuron:
    type:     SRMALPHA
    theta:    10
    tauSr:    10
    tauRef:   1
    scaleRef: 2
    tauRho:   1
    scaleRho: 1
training:
    error:
        type: NumSpikes
        tgtSpikeRegion: {start: 0, stop: 300}
        tgtSpikeCount: {true: 60, false: 10}
path:
    root_dir:   examples/demo/datasets/NMNIST/
